FROM eclipse-temurin:21.0.3_9-jdk-alpine as builder

COPY pom.xml /home/app/pom.xml
COPY .mvn /home/app/.mvn
COPY mvnw /home/app/mvnw
COPY src /home/app/src

WORKDIR /home/app
RUN --mount=type=cache,target=/root/.m2 ./mvnw package -DskipTests


FROM eclipse-temurin:21.0.3_9-jre-alpine as runner

RUN apk add --no-cache coreutils

COPY entrypoint-basic.sh /entrypoint.sh

COPY --from=builder /home/app/target/app.jar /app.jar

ENTRYPOINT [ "/entrypoint.sh" ]
