FROM ghcr.io/graalvm/native-image-community:25.0.2-muslib AS builder

COPY pom.xml /home/app/pom.xml
COPY .mvn /home/app/.mvn
COPY mvnw /home/app/mvnw
COPY src /home/app/src

WORKDIR /home/app
RUN --mount=type=cache,target=/root/.m2 ./mvnw --batch-mode package -Pnative -DskipTests


FROM alpine AS runner

RUN apk add --no-cache coreutils

COPY entrypoint-native.sh /entrypoint.sh
COPY --from=builder /home/app/target/app /app

ENTRYPOINT [ "/entrypoint.sh" ]
